### ISSUE TITLE
Conflict with javascript docblock

### ISSUE THREAD

**Issue by minh-upty** [Medalink/laravel-blade#100]
<img width="544" alt="screen shot 2016-03-25 at 11 16 17 am" src="https://cloud.githubusercontent.com/assets/10204620/14036346/5005a032-f27b-11e5-83fa-7695a633c232.png">

javascript code can not highlight anymore.

**Comment by Medalink** [comment]
Can you test this on the latest 1.5.8.3 version and let me know if it's fixed?

**Comment by rzb** [comment]
I just updated the package and the error persists.

**Comment by yasyu** [comment]
![sublimetext3_bladehighlighter_problem](https://cloud.githubusercontent.com/assets/6732669/15958282/94a09ff8-2f2f-11e6-88af-3d3ba748d00c.png)

I faced a resembled problem , too.

**Comment by jbrooksuk** [comment]
Can I get some reproduction code please?

**Comment by zaynali53** [comment]
@yasyu This is not an issue at all. This is how PHP multi line comment works.

*'C' style comments end at the first */ encountered. Make sure you don't nest 'C' style comments. It is easy to make this mistake if you are trying to comment out a large block of code.*

#### Example
```php
<?php
 /*

    echo 'This is a test'; /* This comment will cause a problem */

 */
?>
```

**Comment by yasyu** [comment]
@zaynali53 Ok, thanks. I understood! 

Because there were no such problems when I used sublime text2.  _- I'm using ST3 now_
But I should write an expensive script of interpretability, I agree, too.

**Comment by zaynali53** [comment]
@Medalink Fixed https://github.com/Medalink/laravel-blade/commit/5564765e9d687aae38f3321421abcc886a3ff9cf

![fix](https://cloud.githubusercontent.com/assets/8646770/15961092/5805fa92-2f1c-11e6-8e1b-29f039cf5237.png)

**Comment by rzb** [comment]
I wasn't able to upgrade the package. I assumed that since you've commited to the master branch, I'd be able to update it by running "Package Control: Upgrade Package". Anything I'm missing?

**Comment by zaynali53** [comment]
@rzb please wait for package control to pick up the new laravel-blade release.

**Comment by rzb** [comment]
It just happened. Thanks!
