### ISSUE TITLE
No highlight ( beginning of tag )

### ISSUE THREAD

**Issue by zaynali53** [Medalink/laravel-blade#102]
![capture](https://cloud.githubusercontent.com/assets/8646770/14448628/2f67fc56-001f-11e6-8d4b-884c247e6098.PNG)

**Comment by JayBizzle** [comment]
Seems to work for me :confused: 

![screen shot 2016-04-14 at 22 26 27](https://cloud.githubusercontent.com/assets/340752/14544228/012e6c3a-0290-11e6-81ac-537af02abfe3.png)

**Comment by zaynali53** [comment]
@JayBizzle Not for me 

![one](https://cloud.githubusercontent.com/assets/8646770/14551342/b1fc0784-0286-11e6-931f-919c8a0966d7.PNG)

However, if i put a space before `yield` then it works.

![two](https://cloud.githubusercontent.com/assets/8646770/14551351/cbdcdce6-0286-11e6-8956-f0c2821685e4.PNG)

**Comment by JayBizzle** [comment]
Have you got the latest version that was just released? 1.5.7?

**Comment by zaynali53** [comment]
Yes.

![capture](https://cloud.githubusercontent.com/assets/8646770/14552976/b561b4f8-0297-11e6-899c-ed2d8fbeba3e.PNG)

**Comment by zaynali53** [comment]
This behavior is with all blade 

**`Without Space`**

![capture](https://cloud.githubusercontent.com/assets/8646770/14553745/1acafd90-029d-11e6-9c86-1d7238687e6c.PNG)

**`With Space`**

![capture2](https://cloud.githubusercontent.com/assets/8646770/14553748/21233dc4-029d-11e6-8947-2877cf88748e.PNG)

**Comment by JayBizzle** [comment]
Latest Sublime?

**Comment by zaynali53** [comment]
@JayBizzle Yes. Dev Channel. Build 3111.

**Comment by JayBizzle** [comment]
Hmmm...i'm on 3103 from the Stable Channel.

Perhaps something broke in later builds?

**Comment by zaynali53** [comment]
Yes. I installed the stable release and yes it is working there.
