### ISSUE TITLE
Highlitghting is broken after update to Sublime 3 Build 3114

### ISSUE THREAD

**Issue by overcrookd** [Medalink/laravel-blade#105]
I've tried closing all files in all projects, removing the package, closing Sublime, opening it and installing the package again, the issue persists.

![sb3_build_3114](https://cloud.githubusercontent.com/assets/1321256/15247290/f290522c-191b-11e6-97ee-5acda0f535ee.png)

**Comment by vanekj** [comment]
#106 This should repair it

**Comment by ndran** [comment]
How do you edit that file? Where does it live on my computer ( on a mac )

**Comment by overcrookd** [comment]
@ndran You need to install the PackageResourceViewr package first.

Then `Ctrl (Command for mac)+Shift+P` -> Open Resource -> Laravel Blade -> blade.sublime-syntax

This will open the file for you. Edit and save as usual

**Comment by ndran** [comment]
Thank you! @overcrookd

**Comment by ahmadryo** [comment]
thanks @overcrookd

**Comment by verchielxy** [comment]
Thank you!  @overcrookd
