### ISSUE TITLE
HTML Autocomplete Not working 3114

### ISSUE THREAD

**Issue by saulhudson** [Medalink/laravel-blade#107]
Hi

After updating to Sublime 3114 when entering the "</" of a closing HTML tag in a Blade template doesn't trigger the auto completion of the tag. If I set the syntax highlighting to HTML it works fine so I can only assume this is an issue with the Blade syntax highlighting.

Thanks

**Comment by overcrookd** [comment]
From what I've tested it seems to be working, possibly related to #106 have you tried that fix?

**Comment by saulhudson** [comment]
By the time I checked my sublime had already updated and included the fix to this package. I can confirm that fix has also fixed this issue.
