### ISSUE TITLE
@stack and @push/@endpush breaks highlighting in Sublime Text 3 Build 3114

### ISSUE THREAD

**Issue by haxzorer** [Medalink/laravel-blade#108]
Syntax highlighting breaks when using either @stack or @push/@endpush in Sublime Text 3 Build 3114.

![skarmavbild 2016-05-14 kl 10 50 47](https://cloud.githubusercontent.com/assets/11200663/15267410/d3307898-19c1-11e6-8dfd-0e2b77e0b997.png)

Screenshot from Sublime Text 3 Build 3103 for reference

![skarmavbild 2016-05-14 kl 10 52 41](https://cloud.githubusercontent.com/assets/11200663/15267426/1a1f6eda-19c2-11e6-91bf-043c1b6b224d.png)

**Comment by jdavidbakr** [comment]
Not just those but it looks like any "@" prefixed command has blown up formatting with build 3114.

**Comment by nobreferreira** [comment]
Yeah it looks like any '@' got problems.

**Comment by zaynali53** [comment]
These directives are not supported yet. There is PR #98. But not merged. 

I manually added these directives and here's the output.

![capture2](https://cloud.githubusercontent.com/assets/8646770/15272331/88cd51ba-1a28-11e6-9501-9bfe373ef36a.JPG)

I'm using the latest build 3114 and package version v1.5.8

![capture3](https://cloud.githubusercontent.com/assets/8646770/15272336/a9fd2d24-1a28-11e6-85a6-2b970c7109c7.JPG)

**Comment by haxzorer** [comment]
Hmm,  I see! But, how come it worked with those directives in build 3103, with version 1.5.8, and without the patch?

**Comment by zaynali53** [comment]
No. These directives were not supported however get highlighted because of the @ symbol in 3103 reference.

The directive didn't turned red according to your color scheme.

![capture](https://cloud.githubusercontent.com/assets/8646770/15272951/5c853a9e-1a3e-11e6-9a5e-0f2cf8b439b1.JPG)

See #110

**Comment by verchielxy** [comment]
![8e9fabdb-42ac-4b43-8fea-84957d3377b0](https://cloud.githubusercontent.com/assets/6937714/15278050/73093cfe-1b45-11e6-8363-07d00218a70e.png)
![72f8e171-f6bd-4d53-b8a5-17b205404508](https://cloud.githubusercontent.com/assets/6937714/15278052/77d32cfe-1b45-11e6-87bc-c61d0acd87ed.png)

**Comment by furey** [comment]
Hi @zaynali53,

Excuse my ignorance, but how did you manually added those directives?

Cheers!

**Comment by zaynali53** [comment]
@furey I cloned the repository in my sublime packages folder and then manually added those directives in the `blade.sublime-syntax` file.

I've also made a PR (#109) too. So after merged it'll resolve that issue.

**Comment by furey** [comment]
@zaynali53 Ah, okay, thanks!

**Comment by mydnic** [comment]
:+1:
I hope it will be solved soon

**Comment by Medalink** [comment]
Added.

**Comment by sahibalejandro** [comment]
I'm using a package that exposes custom blade directives like `@form($model)`, when I use these directives highlighting breaks, same as: https://github.com/Medalink/laravel-blade/issues/110

How we can use custom "no official" directives without breaking the highlighting?
