### ISSUE TITLE
Un-supported directives are breaking syntax highlighting

### ISSUE THREAD

**Issue by zaynali53** [Medalink/laravel-blade#110]
In the latest build of sublime. Maybe something has changed which is causing the un-supported directives behave incorrectly.

In my test. Putting () parenthesis after the un-supported directives `( Those which are not added in the package yet )` are causing highlight break issue. 

# Example

**1:** Un-supported direcitve **Without** Parenthesis. `Don't Break`

![capture1](https://cloud.githubusercontent.com/assets/8646770/15273213/96d2add2-1a46-11e6-9dd0-f5c3f9283d09.JPG)

**2:** Un-supported direcitve **With** Parenthesis. `Breaks all syntax highlight after`

![capture2](https://cloud.githubusercontent.com/assets/8646770/15273217/ad8143f4-1a46-11e6-9386-445250725c86.JPG)

**3:** Supported directive

![capture3](https://cloud.githubusercontent.com/assets/8646770/15273128/b248023a-1a44-11e6-89eb-9909395509bc.JPG)

**Comment by DNABeast** [comment]
Oddly enough putting a second close bracket will fix the highlighting. (but of course, break the code)
ie. @stack())

**Comment by Medalink** [comment]
This has been fixed.
