### ISSUE TITLE
Highlighting breaks with multiple lines array

### ISSUE THREAD

**Issue by jenky** [Medalink/laravel-blade#111]
This works

<img width="818" alt="screen shot 2016-05-16 at 10 03 51 am" src="https://cloud.githubusercontent.com/assets/1808758/15280086/818dae34-1b56-11e6-9883-1143a7b6a395.png">

But this doesn't

<img width="412" alt="screen shot 2016-05-16 at 10 04 08 am" src="https://cloud.githubusercontent.com/assets/1808758/15280098/8961e72e-1b56-11e6-8486-e9c4b68dc797.png">

**Comment by Medalink** [comment]
This has been fixed.
