### ISSUE TITLE
Two Laravel Blade FileType when install laravel-blade

### ISSUE THREAD

**Issue by victormongi** [Medalink/laravel-blade#112]
This Works
![1](https://cloud.githubusercontent.com/assets/5617746/15314809/a9c888ec-1c46-11e6-9eb6-42e85a7cc9e7.png)

But this doesn't
![2](https://cloud.githubusercontent.com/assets/5617746/15314810/a9cb1a30-1c46-11e6-8eb0-9fec3dbafbd5.png)

I can't set default current extension for the works one at View->Syntax->Open all with current extension  as... It will return to the not working file extension...
![image](https://cloud.githubusercontent.com/assets/5617746/15314990/9d317f48-1c47-11e6-984a-676f9aafeeb6.png)

**Comment by Medalink** [comment]
Try uninstalling blade and see if you still have a Laravel Blade definition. If so check your ```%appdata%Sublime Text 3\Packages\User\ ``` folder for any local copies of the highlighter and remove them. Then reinstall the highlighter package from your package manager.

**Comment by victormongi** [comment]
Thanks Medalink... That solved my problem...
