### ISSUE TITLE
Structured data issue

### ISSUE THREAD

**Issue by BojanKogoj** [Medalink/laravel-blade#114]
When I try to use [Structured data](https://search.google.com/structured-data/testing-tool) (application/ld+json) in blade it looks all weird.

![screenshot from 2016-05-19 09-53-43](https://cloud.githubusercontent.com/assets/634075/15386352/a78707b8-1da7-11e6-979b-18d805f6e616.png)

Any ideas on this?

**Comment by Medalink** [comment]
This is a known issue and currently no workaround.
