### ISSUE TITLE
Suport for envoy files?

### ISSUE THREAD

**Issue by jopereyral** [Medalink/laravel-blade#117]
Exist any suport for envoy.blade files?

<img width="350" alt="screen shot 2016-05-23 at 2 57 00 pm" src="https://cloud.githubusercontent.com/assets/5117647/15482691/9e5cba64-20f6-11e6-8df5-03e6e0550a70.png">

**Comment by Medalink** [comment]
These will now show up under the custom compiler highlight rules. Is this enough or so do you think we should color the Envoy compilers a different color so the user knows when they are using specific envoy code?

**Comment by jopereyral** [comment]
I think it's enough because envoy files aren't updated frecuently. Thanks
