### ISSUE TITLE
@continue and @break directives not highlighted

### ISSUE THREAD

**Issue by paulhbarker** [Medalink/laravel-blade#120]
Seems like the @continue and @break Blade directives for loops added in 5.2 aren't supported?

**Comment by zaynali53** [comment]
These directives are supported. 
![capture](https://cloud.githubusercontent.com/assets/8646770/15727191/69042ba2-286e-11e6-94bc-422f186e8e09.PNG)

**Comment by paulhbarker** [comment]
Yes, those work, I was talking about the one-line functionality:
![image](https://cloud.githubusercontent.com/assets/7366567/15727422/2e1e2dd4-280b-11e6-8478-cbe409884c8b.png)

**Comment by zaynali53** [comment]
@paulhbarker Yes i got it. Going to make a PR for that. 

Fixed preview

![capture](https://cloud.githubusercontent.com/assets/8646770/15727615/44945ece-2871-11e6-9b19-fb057033bb9c.PNG)
