### ISSUE TITLE
commenting inside blade

### ISSUE THREAD

**Issue by ctf0** [Medalink/laravel-blade#125]
thanx for the last update, however now we cant make an html comment as all now is being treated as blade comments only.

also the blade comment end is not colored mainly because the `{{--` have a scope of `punctuation.definition.comment.html` while the other side `--}}` doesn't have it.

**Comment by ctf0** [comment]
i think something went terribly wrong with the last comment as now non of the html autocompletion work.

**Comment by zaynali53** [comment]
@ctf0 yes. i've reverted the 1.5.8.8 release and re-write the scopes for blade and commenting. In my tests blade commenting and html features are working. please wait for the packagecontrol to get the new updates for laravel-blade 1.5.8.9.

About html comments then there's a issue in the scope as i've seen that laravel-blade is using `text.html.basic` as a html syntax highlighter and then does the rest of the work for blade. So in that both comment options becomes a trade off as both html elements and blade directives are having this scope in them and that was the issue laravel-blade was having previously. 

I made the blade comments as the default for now as it'll serve the purpose of the comments and doesn't break. But i'm figuring out for the way around having both option.

**Comment by ctf0** [comment]
the comment could use like b4, inside the double mustache the blade comment get triggered, outside it the html gets triggered.

**Comment by zaynali53** [comment]
@ctf0 problem remains the same and this issue was raised several times because inside the double mustache the scope is php so php comments gets triggered. so you'll get this output

```php
// {{ $name }}
```

**Comment by zaynali53** [comment]
@ctf0 Ok i did a little tweak and this is what i get. 

![captu2re](https://cloud.githubusercontent.com/assets/8646770/15990214/3af60d12-30a6-11e6-881d-21d841aa0cf4.PNG)

**Comment by ctf0** [comment]
all good, except one tiny small edit, the php tag should be within html not blade comment, but this is a minor feature and u can close the issue if u want to :)

**Comment by zaynali53** [comment]
@ctf0 Thanks :) and i just used blade comment for php because html comment breaks the highlight.

![captu2re](https://cloud.githubusercontent.com/assets/8646770/15990408/efa46098-30aa-11e6-95fa-ea2d6d679eaf.PNG)

**Comment by ctf0** [comment]
i understand what u mean, but as php is derived from html so the comment should always be the html not blade regardless of the code highlight., however here is what i found

`<?php  echo "string"; ?>|` will give blade comment, add a space after the `?> |` and u will get an html comment instead.

**Comment by zaynali53** [comment]
@ctf0 Sure, i'll add this feature in the next release.

And i couldn't reproduce this in my sublime. 
`?>|` and `?> |` both gives the html comment as the cursor is in the html scope.

**Comment by ctf0** [comment]
thats weird maybe its something related to my machine then 👀

**Comment by zaynali53** [comment]
@ctf0 Sorry, but I've to revert back to the blade comments as many devs file this html comment as an issue.

**Comment by ctf0** [comment]
@zaynali53 its okay, np , thanx again for ur hard work :metal:

**Comment by ctf0** [comment]
break again 😢

**Comment by zaynali53** [comment]
@ctf0 this is a known issue. please wait. i'm fixing it

**Comment by zaynali53** [comment]
@ctf0 Fixed https://github.com/Medalink/laravel-blade/commit/9cd42653c41a0fd809b342c85dce2e55998b4ec2. Now default would be blade comments.

**Also:** It was conflicting within embed block code like (css, js and php). This commit has fixed those unexpected behaviors too, now they'll use their own comments on trigger.

**Comment by ctf0** [comment]
perfect 👍
