### ISSUE TITLE
latest update causing html/php auto close tags no longer working

### ISSUE THREAD

**Issue by tommyys** [Medalink/laravel-blade#127]
for example
**foo.blade.php**

typing `</` after `<div>` no longer auto close tag.

**Comment by zaynali53** [comment]
Fixed https://github.com/Medalink/laravel-blade/commit/e3fd5a43b534719c57993cf1de89d3d9cb4cca42

**Comment by tommyys** [comment]
thanks... that was pretty quick :+1:
