### ISSUE TITLE
Windows Subl 3 install package

### ISSUE THREAD

**Issue by dwijpr** [Medalink/laravel-blade#129]
Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.6.0

**Comment by zaynali53** [comment]
@dwijpr Fixed

**Comment by AndyClausen** [comment]
I got the same problem, and visiting that page indeed gives a 404.
One thing I noticed is that the link is actually https://codeload.github.com/Medalink/laravel-blade/zip/1.6.0. <- with a dot in the end. I tried putting a 1 after, and this makes it download 1.6.0.1, but I'm not sure if that's the latest?
