### ISSUE TITLE
1.6.0 Not working in Sublime 3114

### ISSUE THREAD

**Issue by Souldat** [Medalink/laravel-blade#130]
Syntax highlighting is not working correctly. I've tried uninstalling, restarting, etc and the problem persists.

![screen shot 2016-07-27 at 11 49 26 am](https://cloud.githubusercontent.com/assets/7997256/17185897/324f5872-53f0-11e6-9ede-185a02e51044.png)

**Comment by zaynali53** [comment]
@Souldat  I'm not able to reproduce this issue. My sublime version is 3114 and i re-installed the package.
Here is my output

![capture](https://cloud.githubusercontent.com/assets/8646770/17190772/8a96cb80-5460-11e6-9d0a-8d901b2d3955.PNG)

**Comment by Medalink** [comment]
Can you give us a list of your other plugins and your current theme @Souldat ?

**Comment by Souldat** [comment]
@Medalink I just tried with a fresh install of Sublime, no additional plugins or themes. Only package control. Very strange because it's working fine on my other systems.

**Comment by venturion** [comment]
@Souldat  i can see this bug when i'm using the plugin with monokai color schemes!

**Comment by bradgenereux** [comment]
@venturion Hmm interesting. Monokai looks fine on my other computers. Just the one computer that has issues, both have the exact same setup.

**Comment by Souldat** [comment]
@venturion Hmm interesting. Monokai looks fine on my other computers. Just the one computer that has issues, both have the exact same setup.
