### ISSUE TITLE
No highlighting for @php and @endphp

### ISSUE THREAD

**Issue by d88pak** [Medalink/laravel-blade#132]
Hi,

Just recently discovered that we can use @php and @endphp inside blade instead of <?php ?> but its not highlighted. Everything is white.

**Comment by zaynali53** [comment]
@d88pak Fixed. cdbb0fcf5b47b1607391927994d3fa435bbb5b0a

![capture](https://cloud.githubusercontent.com/assets/8646770/19012533/21de89fc-87d2-11e6-926c-d75652ed6356.PNG)

**Comment by d88pak** [comment]
Workking now

Thanks!

**Comment by indigoram89** [comment]
that is cool!
but one line directive not work:

[
<img width="579" alt="screen shot 2016-10-05 at 08 22 35" src="https://cloud.githubusercontent.com/assets/10687211/19101944/e49dd4f2-8ad4-11e6-83a6-cd363f54d44b.png">
](url)

**Comment by indigoram89** [comment]
if close it, then all is well, but it is not practical :)

<img width="581" alt="screen shot 2016-10-05 at 08 23 24" src="https://cloud.githubusercontent.com/assets/10687211/19101971/1b75db5a-8ad5-11e6-9904-3e3b97b6a212.png">

**Comment by Medalink** [comment]
@indigoram89 try doing this:

```php
@php $foo = 'bar'
```

**Comment by indigoram89** [comment]
@Medalink then not will a close tag:

![c09cbf0f82](https://cloud.githubusercontent.com/assets/10687211/19142621/763f4b16-8ba7-11e6-855e-6da93cd30b74.jpg)
