### ISSUE TITLE
Custom directive support

### ISSUE THREAD

**Issue by jhoff** [Medalink/laravel-blade#138]
Is it at all possible, through configuration, to support custom directives? I have a few across my projects that would be nice to have proper highlighting for. Not a big deal, just wondering if it's possible.

Thanks!

**Comment by heavybeard** [comment]
Hi @jhoff,
if your directives are globals and commons to use, they can be added on plugin script.
I don't believe (but i'm not sure about that) there's a support key for custom directives, but it's a very good idea.

If you want support to add it on your local files plugin i can help you

**Comment by Medalink** [comment]
The @ is setup to handle custom compilers. So doing something like @custom() would work. Outside of that what are you looking to add?

**Comment by jhoff** [comment]
As far as I can tell, the highlighting only works for the core directives ( extends, section, etc ). Any custom directive defined does not highlight.

![image](https://cloud.githubusercontent.com/assets/627060/22388263/64817910-e4a5-11e6-922f-a510da985c7f.png)

**Comment by Medalink** [comment]
Custom compiler highlight broke at some point. Fixed and pushed out the release. Let me know if that does what you are looking for.

7edbec6828231f26e709f3637a683a17db0352ed

**Comment by jhoff** [comment]
Cool! I'll watch for packagecontrol.io to see the new release and i'll try it out!

**Comment by jhoff** [comment]
Package Control updated and it looks great. Thanks for the fix.
