### ISSUE TITLE
Issues with installing

### ISSUE THREAD

**Issue by bartclaeys** [Medalink/laravel-blade#139]
"Search for Laravel Blade and install it, it's just that simple"

Well, not really.

1. Install Sublime Package Control
2. Restart Sublime Text
3. In Sublime Text, go to Preferences > Package Control
4. Find "Install Package" and click it.
5. Search for "Laravel Blade", click it.
6. Restart Sublime Text.
7. Close and re-open your Blade file.

#3, #4 and especially #7 are important to mention.

**Comment by redgluten** [comment]
Well that seems like a perfect plan for a [pull-request](https://help.github.com/articles/creating-a-pull-request/) on the [README file](https://github.com/Medalink/laravel-blade/blob/master/readme.md).

**Comment by Medalink** [comment]
Are you asking for a change to the installation instructions?
