### ISSUE TITLE
Ommitting @endphp causes syntax issue

### ISSUE THREAD

**Issue by kmmathis** [Medalink/laravel-blade#140]
I've noticed that the highlighter requires @endphp even though it is an optional tag. At first I thought it was an issue with the template that I was using, but I found out that in Blade, @endphp is optional. See the discussion here: https://discourse.roots.io/t/sublime-text-blade-highlighting-issue/8803

Basically, the highlighter assumes everything after @php is PHP if it isn't explicitly closed out.

Here is some sample code:
``` Blade
@while (have_posts()) @php(the_post())
    @include ('partials.content-'.(get_post_type() !== 'post' ? get_post_type() : get_post_format()))
@endwhile
```

**Comment by Leland** [comment]
Exact same issue I'm running into (and the same theme, hey). Really makes development difficult.

<img width="648" alt="screen shot 2017-02-21 at 1 15 31 pm" src="https://cloud.githubusercontent.com/assets/714017/23178296/dda39f08-f837-11e6-9cc4-01e5b7ec9fe1.png">

**Comment by Medalink** [comment]
Just checking back in here @Leland @kmmathis to make sure the fixed I pushed out is working?

**Comment by kmmathis** [comment]
It's working like a charm. Thank you!
