### ISSUE TITLE
No @verbatim directive

### ISSUE THREAD

**Issue by amcardwell** [Medalink/laravel-blade#142]
I dont see support for the `@verbatim` directive?

[https://laravel.com/docs/5.4/blade#displaying-data](url)

**Comment by zaynali53** [comment]
Fixed e686f295b34f22f5cdb51284d41043e3547f95ee

![capture](https://cloud.githubusercontent.com/assets/8646770/25863817/a96bedec-3506-11e7-912c-f60db970a8a8.JPG)

**Comment by Medalink** [comment]
Thanks @zaynali53
