### ISSUE TITLE
Package does not work when installed alongside 'CSS3' package.

### ISSUE THREAD

**Issue by ryami333** [Medalink/laravel-blade#143]
When both are installed, and a php/blade file is opened, this error occurs:

```
Error loading syntax file "Packages/Laravel Blade Highlighter/blade.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

Using build 3126 of Sublime. Removing either package fixes the issue.

**Comment by ryami333** [comment]
Not sure on which package the fault lies, so have opened the equivalent issue on the `CSS3` repo: https://github.com/y0ssar1an/CSS3/issues/78

**Comment by novusidea** [comment]
I have the same problem:

[https://i.imgur.com/x5x4DMa.png](https://i.imgur.com/x5x4DMa.png)

If it helps, I am using Windows 10.

**Comment by django-wong** [comment]
+1 same here

**Comment by verchielxy** [comment]
+1 same here

**Comment by VermillionOne** [comment]
+1 and such

**Comment by DylanCa** [comment]
Still nothing ? Not cool :/

**Comment by joonkui95** [comment]
+1 same problem

**Comment by vvatitv** [comment]
+1 same problem

**Comment by danh20051995** [comment]
+1 same problem on MAC OS X

**Comment by hassanazimi** [comment]
+1

**Comment by rjfernandes** [comment]
+1

**Comment by hassanazimi** [comment]
It's a conflict with some package. I deleted sublim text and installed version 3 again and now no problem.

**Comment by justindantzer** [comment]
I uninstalled the CSS3 package and the problem went away, which seems to verify others findings.
