### ISSUE TITLE
Broken Font Settings.

### ISSUE THREAD

**Issue by umeshmk** [Medalink/laravel-blade#145]
Font settings gets broken if package is installed.
See image
![image](https://cloud.githubusercontent.com/assets/19268386/26669113/39c4dffa-46ca-11e7-8976-f17f9e1c68ad.png)

**Comment by Medalink** [comment]
I have not seen this issue before. It might be a conflict with your specific theme? Testing it locally with my font/theme works. Swapping to the defaults work.

**Comment by umeshk149** [comment]
Can you try with the same preferences as in screenshot ?
