### ISSUE TITLE
@if highlighting no longer working correctly

### ISSUE THREAD

**Issue by stuartcusackie** [Medalink/laravel-blade#151]
Hi,

My blade files are no longer being highlighted correctly. Any @if statements that appear within quotes are not closing correctly and the highlight that is usually used between quotes runs all the way through the rest of the code.

For example:

`<p class="first-class @if(x==true) second-class @endif">Text</p>`

The above statement will cause string highlighting to continue all the way down the code.

I think the update 2 days ago (15/08/2017) might have caused this issue.

I'm not sure if this applies to @for and the other blade control structures.

Thank you for the package!

**Comment by piperone** [comment]
Can confirm. This is what it suddenly started looking like today for me:

![syntax](https://user-images.githubusercontent.com/351744/29411005-68ad2f96-8353-11e7-8d7f-cbdd7dff4795.png)

**Comment by mc0de** [comment]
can confirm that too, it displays incorrectly

**Comment by jakebathman** [comment]
Let me see if I can get a fix working, sorry about that @piperone

**Comment by piperone** [comment]
No problem @jakebathman. I just forked, reverted and added my repo to Sublime packet manager until there's a fixed release.

**Comment by Medalink** [comment]
Pushed out the revert, package control should pick up the changes within the hour.

**Comment by jakebathman** [comment]
Inline blade directives present a fun challenge, so I'm continuing to work on a solution that passes any test I can think of. With the original matching, here's how it matches:

![sublime_text_2017-08-17_09-45-20](https://user-images.githubusercontent.com/43112/29418060-f4bd4ff2-8330-11e7-8d9e-41a495bac8d5.png)

Trying to convince regex to match up until the final closing `)`, should have it figured out soon and will let everyone know for testing.

**Comment by Medalink** [comment]
@jakebathman thanks for your work on this 👍  let me know if I can be of any help.

**Comment by stuartcusackie** [comment]
Nice once guys. Really appreciate what you're doing there. If I understood the code I would help out.

**Comment by jakebathman** [comment]
Alrighty, submitted PR #155 with a new matching strategy. Let me know if this works with any existing blade files that everyone has.

**Comment by stuartcusackie** [comment]
All my blade seems fine now. Thank you.

**Comment by jakebathman** [comment]
After a few weeks, I've not seen any weirdness with this new matching regex, so it looks like PR #155 is good to go.
