### ISSUE TITLE
Not working in build 3126

### ISSUE THREAD

**Issue by alo0oz** [Medalink/laravel-blade#160]
When opening a blade.php file following error message are shown

> error loading syntax file
"packages/laravel-blade/blade.sublime-syntax":
Apparent recursion within a with_prototype action:25000 context sanity limit hit

**Comment by alo0oz** [comment]
Solved the problem by disabling the php package.

**Comment by dikiaap** [comment]
Same. Build 3143 also not working

**Comment by dikiaap** [comment]
I'm not sure. But I have 2 CSS packages, CSS and CSS3. Try disable CSS and it's working for me.
