### ISSUE TITLE
not working in 3143

### ISSUE THREAD

**Issue by maxca** [Medalink/laravel-blade#161]
Package Control

The following incompatible package was found installed:

Laravel Blade Highlighter

This is usually due to syncing packages across different machines in a way that does not check package metadata for compatibility.

Please visit https://packagecontrol.io/docs/syncing for information about how to properly sync configuration and packages across machines.

To restore package functionality, please remove each listed package and reinstall it.

**Comment by Medalink** [comment]
Can you give some background on what caused this? Was this a new install of the highlighter? What OS are you running?

Thanks
