### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by 28development** [Medalink/laravel-blade#163]
A couple of days ago the package does not work anymore I get this error message:

> Error loading syntax file 'Packages/Laravel Blade Highlighter/blade.sublime-syntax': Apparent recursion within a with_prototype action: 25000 context sanity limit hit

**Comment by captbrogers** [comment]
I have found that the last working build of the dev version of Sublime Text is 3154, released November 11th, 2017. The current version, as of this comment, is build 3160.

**Comment by coldfuzion** [comment]
Still a problem.. anything?

**Comment by chadidi** [comment]
I have the same problem. Is there any fix?

**Comment by kjunggithub** [comment]
I also have this problem and just started recently as well.

**Comment by coldfuzion** [comment]
I uninstalled, might have to find a fix ourselves..

**Comment by plakhin** [comment]
seems this won't be fixed until next sublime stable release :( uninstalled

**Comment by chadidi** [comment]
This the first time I have seen an error without any reason it was working why it stopped working I mean the package didn't get updated for a long time and sublime text didn't get updated also. **is it possible that another package causing this problem??**

**Comment by chadidi** [comment]
Removing CSS3 package fixed the problem #143

**Comment by nobreferreira** [comment]
Had the same problem after upgrading ST to build 3170.
Disabling the CSS3 package fixed the problem.

**Comment by trippo** [comment]
Fix problem but not highlighter after an inline style attribute
