### ISSUE TITLE
Missing support for @{{

### ISSUE THREAD

**Issue by powelski** [Medalink/laravel-blade#169]
There is a special `@{{` syntax, as described in the [Blade & JavaScript Frameworks](https://laravel.com/docs/5.6/blade#blade-and-javascript-frameworks) documentation.

However, Laravel Blade Highlighter doesn't seem to recognize it. Take a look at this example:

![curly](https://user-images.githubusercontent.com/2076782/40303790-95122a66-5cf4-11e8-9f10-8d938ce6d26b.png)

Opening curly braces of `{{ $cookies }}` is still highlighted as a content inside other curly braces, even though it was never the case.

**Comment by r4z0rFr** [comment]
Just the same for me for the @csrf 
![screenshot_20180529_004833](https://user-images.githubusercontent.com/11510153/40631165-25af1f26-62da-11e8-93b9-d228d68add1b.png)

It's broke all after syntax coloration .
