### ISSUE TITLE
Updating in ST3 Package Control download URL is a 404

### ISSUE THREAD

**Issue by PouakaiNz** [Medalink/laravel-blade#171]
I was just updating via package control and I'm getting this issue:

Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.6.12.
error: Package Control

Unable to download Laravel Blade Highlighter. Please view the console for more details.

Looks like the link returns 404?

**Comment by Medalink** [comment]
Sorry about that, fixed the URL. Try updating again.

**Comment by PouakaiNz** [comment]
Beauty, All fixed thanks for the package, Keep it up!
