### ISSUE TITLE
set highlighting to specific extensions?

### ISSUE THREAD

**Issue by v3nt** [Medalink/laravel-blade#186]
We're using Sage 9. Its blade files are suffixed with *.blade.php. Setting the formatting to Laravel for this also sets it to all *.php files.

Is there a way to just target the *.blade.php files?

thanks, D.

**Comment by Medalink** [comment]
This package targets specific file types:

`file_extensions: [blade, blade.php]`

This means that by default it does not target `*.php`.

You can try and reset the file association with blade by: `View -> Syntax -> Open all with current extension as... ->[your syntax choice]`
