### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by mrlinnth** [Medalink/laravel-blade#188]
Uninstalled and try to install again.
Got this error in console.

Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.6.18.

**Comment by Thavarshan** [comment]
Min too. Got the same error

Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.6.18.
error: Package Control

**Comment by Corben78** [comment]
Same here. Looks like the URL for downloading configured via package control is not available any more. I see in the package.json it's not codeload but nodeload?

As a workaround, the manual install worked for me (cloning or unzipping this repo to [install-dir]/Packages/laravel-blade)

**Comment by subdesign** [comment]
```
Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.6.18.
error: Package Control

Unable to download Laravel Blade Highlighter. Please view the console for more details.
```
same on Mac

**Comment by mdeprezzo** [comment]
@subdesign doesn't works for me on Linux

**Comment by Corben78** [comment]
> @subdesign doesn't works for me on Linux

It does work on Linux as well, just the path is different. For me it's ```$HOME/.config/sublime-text-3/Packages```

**Comment by mdeprezzo** [comment]
@subdesign i know, i put the file inside Packages dir, but nothing happen

**Comment by Corben78** [comment]
@mdeprezzo maybe you just need to re-select the select hilighting for Laravel Blade? Or check if the Package is blacklisted due to the initial issue. As I'm on Linux as well, I can confirm it does work in general.

**Comment by mdeprezzo** [comment]
> @mdeprezzo maybe you just need to re-select the select hilighting for Laravel Blade? Or check if the Package is blacklisted due to the initial issue. As I'm on Linux as well, I can confirm it does work in general.

i'll try thanks for the suggestion!

**Comment by ganeshkanadeaplswd** [comment]
![Capture](https://user-images.githubusercontent.com/62798398/83244886-9d68bf80-a1bd-11ea-80ec-68b0bbd62481.PNG)
Worked for me

**Comment by Medalink** [comment]
I fixed a typo in the release name. It should install correctly now.

**Comment by Corben78** [comment]
@Medalink 
> I fixed a typo in the release name. It should install correctly now.

Thanks for the quick response to this issue. Where was that typo? On package control's end as I don't see a commit with that fix on this repo? As of right now it does not install for me, but maybe package control just needs some time to adapt.
