### ISSUE TITLE
Doesn't highlight alpinejs properly.

### ISSUE THREAD

**Issue by OzanKurt** [Medalink/laravel-blade#196]
![image](https://user-images.githubusercontent.com/8682003/210159212-5c53a051-1cab-4bde-b3b3-99a2ddfaebf3.png)

**Comment by OzanKurt** [comment]
![image](https://user-images.githubusercontent.com/8682003/210159214-1b0fefeb-26e3-46f0-9f1e-43c6c2c5f0cb.png)

**Comment by deathaxe** [comment]
I'd say this requires a dedicated syntax and is out of scope of a basic "Blade" syntax. Can't be expected to work as combinding Blade and vue.js wouldn't.

**Comment by deathaxe** [comment]
We can at least make sure attribute values are scoped as string after `@click`. 

Scoping attribute values as javascript is however out of scope.

**Comment by OzanKurt** [comment]
Thanks!

**Comment by deathaxe** [comment]
FWIW, to support AlpinJS in Blade templates, install [AlpineJS](https://github.com/SublimeText/AlpineJS) package and create a corresponding `HTML (Blade, AlpineJS)` syntax as outlined in AlpineJS's README.
