### ISSUE TITLE
What is the install command for the plugin 

### ISSUE THREAD

**Issue by devbipu** [Medalink/laravel-blade#200]
Hi there,
You forgot to write the installation manual in your readme.md file. What's the name of the package? I can't find any by searching `Laravel Blade` in sublime text

**Comment by Medalink** [comment]
It's pretty clear from the readme with either the automatic install with package control or manual installation. Please see the readme or check the link to package control for installation instructions.

**Comment by devbipu** [comment]
Yes, I can see but when I search it on package control -> install package, it's not showing there. :(

**Comment by shatterproof** [comment]
Laravel Blade is no longer in the Package Control list (not sure why), it can still be installed manually though.
