### ISSUE TITLE
Syntax coloration in html attributes

### ISSUE THREAD

**Issue by sdebacker** [Medalink/laravel-blade#52]
It would be great to have syntax coloration in html attributes. What do you think ?

**Comment by zaynali53** [comment]
@Medalink This issue has been resolved https://github.com/Medalink/laravel-blade/commit/f338c4106ace9a56d2fdd97886a348c4851998c2

However, Most color schemes don't highlight these kind of edge cases. Only highlights generic scopes in the code so you won't find the difference.

For this reason, i made a new color scheme, focused heavily on JSX (React), ES6 and Laravel Blade. 

### [Acme Color Scheme](https://github.com/zaynali53/acme-color-scheme)
![capture](https://cloud.githubusercontent.com/assets/8646770/16539207/571efe2c-4055-11e6-8285-2edafcaecb5d.PNG)
