### ISSUE TITLE
{!! !!} Syntax not being highlighted

### ISSUE THREAD

**Issue by davidxd33** [Medalink/laravel-blade#61]
The new raw html {!! !!} tags are not being highlighted. I'm using version v.1.1.3 and Sublime Text 3. 

![Sublime](http://i.imgur.com/H2eWUWy.png)

Edit: Noticed the actual commit was a revert, so I guess this is a feature request now.

**Comment by reinink** [comment]
I'd love to see this functionality added, now that Laravel 5 is right around the corner. That is all, thanks. :)

**Comment by duncan3dc** [comment]
:+1:

**Comment by Medalink** [comment]
Fixed in v1.5.0.

**Comment by reinink** [comment]
Nice! Thanks @Medalink.
