### ISSUE TITLE
.blade.php is not recognized

### ISSUE THREAD

**Issue by loranger** [Medalink/laravel-blade#64]
I have this issue using TextMate 2.0 beta 6

In fact I always had this issue : `file.blade.php` are not recongized as blade until you select the Blade syntax. Then textmate remembers your choice for this only file and use Blade everytime you open the file, but the extension detection does not work for a reason I can't figure out.

Am I alone ? Did I miss something ?

**Comment by Medalink** [comment]
This should be fixed now. If not please open a new issue.
