### ISSUE TITLE
Regression? Keywords and at-sign are now different colors

### ISSUE THREAD

**Issue by julien-c** [Medalink/laravel-blade#66]
Not sure whether this is a bug or feature, but I think it looks way better in the first screenshot. FWIW my theme is `Mac Classic.tmTheme`.

`v1.1.3`:
![screenshot 2014-12-22 a 12 02 10](https://cloud.githubusercontent.com/assets/326577/5524403/cf4b8e1c-89d4-11e4-914e-dd26213cbcca.png)

`v1.1.4`:
![screenshot 2014-12-22 a 12 03 10](https://cloud.githubusercontent.com/assets/326577/5524404/d66cd818-89d4-11e4-9ba2-0801a4637b92.png)

**Comment by Medalink** [comment]
This should be fixed in v1.5.0. Can you verify? Mine is working correctly.
