### ISSUE TITLE
Multiline highlighting breaks after function call in conditional expressions

### ISSUE THREAD

**Issue by Stichoza** [Medalink/laravel-blade#67]
![screen shot 2015-02-11 at 22 42 08](https://cloud.githubusercontent.com/assets/1139050/6153631/65c85950-b23f-11e4-91a0-b96fdc808cde.png)

This obviously doesn't happen on single line.

**Comment by Medalink** [comment]
Does this work in native PHP?

**Comment by Stichoza** [comment]
Yes, it does.

**Comment by zaynali53** [comment]
This has been fixed #118 

![capture](https://cloud.githubusercontent.com/assets/8646770/15715132/c36375e0-2836-11e6-8cbd-c0cd0b21775f.PNG)
