### ISSUE TITLE
Disable blade comments

### ISSUE THREAD

**Issue by tuurbo** [Medalink/laravel-blade#70]
Is there a way to revert "blade style comments" that were introduced in v1.5.2 or a way to use v1.5.1 without manually installing your package?

**Comment by Medalink** [comment]
Not without manual install. Is there an issue with it?

**Comment by tuurbo** [comment]
I just prefer to have html comments since i never really have a use for blade comments

**Comment by miguelgarcia7** [comment]
It would be nice to have both options. I can see where sometimes it is nice to just do HTML comments vs blade style comments. Fantastic package though!
