### ISSUE TITLE
Change Blade Delimiters Feature Request

### ISSUE THREAD

**Issue by NgYueHong** [Medalink/laravel-blade#71]
When developing Laravel with AngularJS, there is a need to change blade delimiters. A good tutorial is here: http://laravelsnippets.com/snippets/using-laravel-blade-with-angularjs-templates-redux-alternate-method

Hope this syntax package come with the features allow us to change it so that we can use this syntax package when developing Laravel with AngularJS.

**Comment by jbrooksuk** [comment]
I don't think that this can be achieved, simply because the syntax needs to know at run-time what tags it's looking for.
