### ISSUE TITLE
Typo in v1.5.3 tag

### ISSUE THREAD

**Issue by paulboco** [Medalink/laravel-blade#74]
Package control is trying to upgrade laravel-blade to version "v1.5.3" but that tag does not exist.  New version was tagged as "1.5.3" omitting the "v". As a result, package control cannot find the download as shown by this message:
    
    Package Control

    Unable to download Laravel Blade Highlighter. Please view the console for more details.

A look at the console reveals:

    Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/v1.5.3.

**Comment by Medalink** [comment]
Fixed, thanks.
