### ISSUE TITLE
Highlighting breaks on latest Sublime 3

### ISSUE THREAD

**Issue by heitorsilva** [Medalink/laravel-blade#76]
Today, I was going to work and my Blade Highlighting broke after getting version 3092 of Sublime Text 3. My color scheme is called IR_Black.

Why is this is happening?

**Comment by Medalink** [comment]
That is a development build that changes syntax highlighting. I am still testing and working out fixes for it. For now you can download the latest stable 3083 and it works just fine.

**Comment by heitorsilva** [comment]
Thanks for the feedback!

I'll leave this issue open, and feel free to close it when you get to the fix.

**Comment by Medalink** [comment]
@heitorsilva Can you provide more details on exactly what is breaking with the blade highlighter?

**Comment by anlutro** [comment]
The problem seems to be that the highlighter starts off in the context of blade syntax as opposed to defaulting to HTML.

**Comment by heitorsilva** [comment]
@Medalink, this is how it is right now:
![image](https://cloud.githubusercontent.com/assets/878699/8238373/9f6af452-15cb-11e5-8e2f-5f07323ac9fe.png)

and this is how it was before:
![image](https://cloud.githubusercontent.com/assets/878699/8238417/e5a9e6da-15cb-11e5-9b63-e92e6b385128.png)

**Comment by heitorsilva** [comment]
Sublime was updated to 3093 today, and laravel-blade is still broken for me...

**Comment by jbrooksuk** [comment]
Grammars should now be looking to use the new `.sublime-syntax` format.

**Comment by danwall** [comment]
I believe the main cause for this is that the php scope changed from `source.php` to `embedding.php`.

A bunch of packages have had issues with this lately.

https://github.com/equinusocio/material-theme/blob/master/prefs/icon_php.tmPreferences

**Comment by Medalink** [comment]
Alright I just pushed 711179b7dc07824f218dee7855f38a0829672efc, this is a complete re-write with the new .sublime-syntax. Please test and leave feedback. Uninstall the package control version and use the manual install for now until we hit the stable release.

**Comment by Medalink** [comment]
Also note that colors changed qutie a bit. I need feedback here on how it's working with your theme. Thanks!

**Comment by anlutro** [comment]
Nice! Using a slightly customized Twilight scheme, blade controls seems to blend in a bit too much with the colour of HTML tags. http://i.imgur.com/etoSLPP.png I think it's because both are "entity.name.tag".

**Comment by Medalink** [comment]
@anlutro yeah they may blend a little much. I am trying out a few themes like Material and it matches well here: http://i.imgur.com/j14VzJ2.jpg?1 The @ symbol is supposed to be a different color than the compiler name but some themes do not highlight some of the meta tags.

**Comment by heitorsilva** [comment]
Looking great now:

![image](https://cloud.githubusercontent.com/assets/878699/8560868/3dc70704-24f3-11e5-8f20-74c7b0a3dffb.png)

I'm using Sublime Text 3 (3094).

Thanks @Medalink

**Comment by anlutro** [comment]
I see that most of the themes do make `@section` etc stand out a bit more, so if nothing gets done I can just change my customized theme.

That being said, I think `keyword.control.php.blade` or something similar is a more fitting scope for things like `@foreach` - it's more consistent with PHP's syntax definition.

**Comment by jbrooksuk** [comment]
Can you tag this so that Package Control upgrades?

**Comment by Medalink** [comment]
@jbrooksuk I will shortly. I want to make sure in the re-write I did not miss anything and it works correctly.

**Comment by jbrooksuk** [comment]
#79 then ;)

**Comment by Medalink** [comment]
@jbrooksuk I went ahead and pushed the pre-release to the ST3 dev builds only. I will check out the other issue, thanks.

**Comment by bcalik** [comment]
I'm on build 3095 and there are weird situations with JS code.
blade else breaks the rest of javascript.

![screen shot 2015-12-31 at 12 38 40](https://cloud.githubusercontent.com/assets/9222368/12063728/3e0ffb68-afbc-11e5-9f1b-355a3884da35.png)

![screen shot 2015-12-31 at 12 38 56](https://cloud.githubusercontent.com/assets/9222368/12063729/3e10ee4c-afbc-11e5-8bc2-52e44e011147.png)

**Comment by rafal-netblink** [comment]
Hi,
I'm on build 3103 with Laravel Highlighter v1.5.6 and it works great a lot of the time, but there seems to be a problem when custom blade tags meet with Blade brackets in one line.

![laravel](https://cloud.githubusercontent.com/assets/4364219/12973699/8c6b7392-d0ae-11e5-9372-77495b341782.png)

Any chance you can do something about it?

**Comment by jp7carlos** [comment]
I have the same problem as rafal-netblink, but it doesn't seem to matter if there is a bracket. Looks like custom blade tags like 
```
@active
@whathever
```
are closing or opening some HTML syntax

**Comment by jbrooksuk** [comment]
I made a new version; https://github.com/jbrooksuk/Sublime-Blade

**Comment by rafal-netblink** [comment]
Works great, thanks James! 

It seems Sublime doesn't know about the new package yet, so for those who install directly from a repository for the first  time, like me - go to Command Palette (ctrl+shift+p on Windows) and find "Package Controll -> Add Repository". Enter the URL James posted and then install the package as you normally would.

**Comment by Medalink** [comment]
@jbrooksuk why don't you join this project as a maintainer instead of forking into another one? It's true that right now I do not have time to fully maintain the project so I am just accepting PR's but I could sure use the help to get the base plugin updated. We can work together as a community to drive this project forward.

**Comment by jbrooksuk** [comment]
Sure. Give me access and I'll contribute back. You were moving too slowly for me to warrant making pull requests, that's not your fault of course :)

**Comment by zaynali53** [comment]
This issue has been resolved.
