### ISSUE TITLE
Blade commenting

### ISSUE THREAD

**Issue by cpriego** [Medalink/laravel-blade#80]
I don't know if is intended to work like this but for a while now, I can no longer use `(Ctrl/CMD) + /` to toggle the blade comments.

Is there anything I can do to fix it? I just have no idea what to modify in order for it to work, I don't want the html comments in my blade files.

What I want in the end is to be able to comment like this:
```php
<div class="form-group">
    <label for="category">Category</label>
    <select id="category" class="form-control" name="category" placeholder="Select category">
        <option value="awesome">Awesome</option>
        {{-- <option value="">Select</option> --}}
        {{--
            @foreach( $categorys as $category )
                <option value="{{ $category->id }}">{{ ucfirst($category->name) }}</option>
            @endforeach
        --}}
    </select>
</div>
```
I don't mind manually installing the package.

Thanks in advance.

**Comment by da-n** [comment]
Just wanted to add I am also seeing this. I've tried several things including removing almost all packages etc but nothing seems to work. Would be great if this could be fixed. Awesome package by the way.

**Comment by jdavidbakr** [comment]
I'm having this issue as well, it is incredibly difficult because I used to do lots of commenting in Blade and now it is nearly impossible to even make the comment tags.

**Comment by djekl** [comment]
This is still an issue, any updates on this?

**Comment by zaynali53** [comment]
Fixed https://github.com/Medalink/laravel-blade/commit/a9a78e63f2d06713af75853a012c23088990dcb2

![fix](https://cloud.githubusercontent.com/assets/8646770/15963169/4312ca04-2f29-11e6-8871-b9bee36b77da.png)

**Comment by djekl** [comment]
How long will this take to get through to sublime package manager? Any ideas?

**Comment by zaynali53** [comment]
@djekl After a new release it'll take an hour or two i guess.

**Comment by jdavidbakr** [comment]
It works!  Thank you!

**Comment by jdavidbakr** [comment]
Ok, I have a strange thing happening since this update, now any files that are in PHP mode are commenting with the blade syntax

![screen shot 2016-06-10 at 9 30 16 am](https://cloud.githubusercontent.com/assets/25177/15967605/fcc920ec-2eed-11e6-99dc-0750a190ed5f.png)

**Comment by djekl** [comment]
Yeah, I am also having this issue. I am now forced to disable this plugin until its fixed unless you can disable the commenting on PHP files

-- 
Alan Wynn
Sent with Airmail

**Comment by jdavidbakr** [comment]
@djekl - I just tried that change and it appears to revert back to using html tags as it was before this morning's update
![screen shot 2016-06-10 at 9 43 43 am](https://cloud.githubusercontent.com/assets/25177/15968031/dc1347f4-2eef-11e6-80b9-a2c809e362ee.png)

**Comment by zaynali53** [comment]
@djekl It is again the same case. i'm detecting the issue. please wait
