### ISSUE TITLE
Can't update, zip link broken?

### ISSUE THREAD

**Issue by anlutro** [Medalink/laravel-blade#82]
```
Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.5.5
```

That doesn't look like the right zip link.

**Comment by Orlmente** [comment]
Same issue here (win7x64 st3 dev3095).

> Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/Medalink/laravel-blade/zip/1.5.5.
>error: Package Control

**Comment by Medalink** [comment]
Fixed, sorry about that.
