### ISSUE TITLE
Incompatible with ST3 Build 3103

### ISSUE THREAD

**Issue by dschu-lab** [Medalink/laravel-blade#89]
Hey there,

could you please update the packages.json to make this work with build 3103 again?

Thanks!

**Comment by andrewcaulfield** [comment]
Confirming that also have an issue with latest Sublime build 3103. 

Cheers.

**Comment by GC-Mark** [comment]
+1

**Comment by djekl** [comment]
Also having issues, seems to work if you uninstall then reinstall. But once you close and re-open Sublime it breaks again...

**Comment by GC-Mark** [comment]
I just reinstalled, and it works. It also works after a sublime restart, so not sure why it doesn't for you @djekl

**Comment by djekl** [comment]
@GC-Mark Open a new window, then a project. It wont work then. I will see if I can get an example made up

**Comment by GC-Mark** [comment]
@djekl just tried that, still works :confused:

**Comment by djekl** [comment]
I only get 30 seconds on cloudy, so before I took the video I removed the package, and then installed it again. Closed all Sublime and it works as before. Then the video was started and you will see the issue cc:// @GC-Mark 

![http://cl.ly/3f3T2o1v3d1f](http://f.cl.ly/items/041R3u1E0x3N1Y3o1X1C/Screen%20Recording%202016-02-09%20at%2010.12%20am.gif)

**Comment by GC-Mark** [comment]
Don't know if it makes a difference, but im using a different project switcher - https://github.com/randy3k/Project-Manager

P.S. What theme are you using, it looks awesome!

**Comment by rginnow** [comment]
+1 Broke when I upgraded my Sublime version to this new build.

Uninstalled and reinstalled, and it worked. Quit, reopened, and it still worked.

Not sure why, but I think it's a small issue to be looked into.

**Comment by djekl** [comment]
@GC-Mark The theme I am using is called [Material Theme](https://github.com/equinusocio/material-theme). It has some bugs with regards to padding, but they are explained in the readme.

Here is my sublime settings file - https://gist.github.com/djekl/8eca76509c7d7915cc14

**Comment by Medalink** [comment]
Looks like they did not roll these out to the dev channel so I missed this before release. For now, use the dev release of 3102 as a workaround until I can get this fixed.

**Comment by stulogy** [comment]
I had this issue too, and rolled back to 3102 as suggested. I'm now getting this weird issue whereby if you put @if () statements inside attributes, then it breaks the rest of the display. See my screenshot.

<img width="350" alt="screen shot 2016-02-09 at 2 26 04 pm" src="https://cloud.githubusercontent.com/assets/2089901/12927976/14eed956-cf39-11e5-842d-36a23b68ea08.png">

It didn't used to do this, it would just highlight everything in the attribute as yellow.

**Comment by cjaoude** [comment]
Reinstalling the package helped. Can't say yet whether issues will crop up.

**Comment by casenjo** [comment]
Tried removing and reinstalling the package but it didn't fix it. Downgraded to 3102 for now, will wait :)

**Comment by Skintillion** [comment]
Uninstall
Close Sublime
Open Sublime
Reinstall
Close Sublime
Open Sublime.

That worked ok for me.

**Comment by razikallayi** [comment]
Incompatible with ST3 Build 3103 

+1

**Comment by Skintillion** [comment]
![image](https://cloud.githubusercontent.com/assets/1521506/12941095/f93d1088-cf83-11e5-81fb-d44535144148.png)

It does work.

**Comment by Skintillion** [comment]
![image](https://cloud.githubusercontent.com/assets/1521506/12941119/22141150-cf84-11e5-9c8e-bd8530eed7da.png)

It works great.

**Comment by marwan2** [comment]
The same issue also with me

**Comment by hollanbo** [comment]
same problem.

**Comment by harhoo** [comment]
Works fine for me; initially it didn't, so Iuninstalled and reinstalled with no success before realising that ST had lost all its syntax associations. So **View > Syntax > Open all with current extension as** and I was back in business.

**Comment by JPT62089** [comment]
> Uninstall
> Close Sublime
> Open Sublime
> Reinstall
> Close Sublime
> Open Sublime.
> 
> That worked ok for me.

This worked for me, too! Thanks, @Skintillion!

**Comment by ben-sharp** [comment]
Following @Skintillion instructions I am able to see my mark up nicely, however the javascript in the section at the bottom of my template now has zero highlighting whatsoever, not sure if this was always the case.

**Comment by stulogy** [comment]
Basic highlighting is working for me now. However when using conditionals it breaks the rest of the highlighting. See my screenshot. This was working before.

**Comment by nuhh** [comment]
As @stulogy said, I have same problem
![error](https://cloud.githubusercontent.com/assets/7755066/12973601/341e8528-d0b6-11e5-8283-a7777edd4198.png)

**Comment by ryanmortier** [comment]
I'm using conditionals and my highlighting seems to be working fine still?

![image](https://cloud.githubusercontent.com/assets/2053960/12980635/4f6a65c8-d0ab-11e5-88b4-af470e5c0637.png)

**Comment by JayBizzle** [comment]
@ryanmortier it doesn't work when your conditional starts within a HTML element

`<div class="@if($something) active @endif">`

**Comment by ryanmortier** [comment]
Oops, sorry I didn't see your comment before I deleted mine or I wouldn't have deleted my comment. Yes you're correct, using it inside an HTML attribute breaks for me too.

**Comment by cklmercer** [comment]
It works for me within an HTML element, but does not work for me within the quoted part of an attribute.

Works
```
<div class="col-md-8 text-content" @if($error) class="error" @endif>
```

Does Not Work
```
<div class="@if($error) error @endif">
```

**Comment by stulogy** [comment]
Agreed.

I think it’s the @ symbols that are throwing off the highlighter. Before this was never a problem, possibly because it ignored @ symbols.

**Comment by JayBizzle** [comment]
I just created a pull request that hacks a fix for this issue. See #92

**Comment by RicardoEmpre** [comment]
For me it has problems with the vuejs line 
`@click="selectResource(resource)". `
If you remove the @ or the parenthesis in that line, it works OK.

![untitled1](https://cloud.githubusercontent.com/assets/8429280/13056456/2fb25a3c-d3f4-11e5-98a4-85548a6583e6.png)

**Comment by estebanprimost** [comment]
@Skintillion :+1: Thanks.

**Comment by jago86** [comment]
Have the same issue @stulogy, @if breaks the rest of display

**Comment by matthewnance** [comment]
Just confirming - Dev build 3107 has not solved the issue even after a fresh install. Strange how inconsistent this seems to be, none of the aforementioned fixes have solved the issue on my end.

**Comment by JTallis** [comment]
I had this issue and I did what some others have done which is reinstalling the package and it seems to work so far for me.
