### ISSUE TITLE
Blade toggle_comment keystroke broken in ST Build 3103

### ISSUE THREAD

**Issue by jdavidbakr** [Medalink/laravel-blade#90]
My ST updated to Build 3103 and now my commenting is not working correctly.  Instead of using the blade comments, it is wrapping in HTML comments

```
{{-- Old comment style --}}

<!-- New comment style -->
```

unless it is a line with an @include or {{ ... }} directive, in which case it comments like this:

```
// {{ trans('page.content') }}
```

which of course isn't even a comment at all.

This definitely changed when I upgraded to ST Build 3103.

**Comment by jamesnine** [comment]
works for me.

![screen shot 2016-02-11 at 8 55 24 am](https://cloud.githubusercontent.com/assets/742462/12983299/8cd52a64-d09d-11e5-8379-0752ea0a3325.png)

I did notice that I initially had issues w/ the plugin after the new ST build update.  These are the steps I took to fix it:

1) Remove the package, then close Sublime
3) Re-open Sublime, then re-install the package
4) Close every open tab that is a .blade.php file in every project, then close sublime
5) Re-open Sublime

**Comment by cklmercer** [comment]
Had this same issue and the 5 step solution provided by @jamesnine worked for me.

**Comment by thekoko** [comment]
Simple as that, thanks @jamesnine

**Comment by jdavidbakr** [comment]
Well, no dice for me ... I did the steps 3 times just to make sure I didn't miss anything.

![screen shot 2016-02-12 at 1 29 55 pm](https://cloud.githubusercontent.com/assets/25177/13017954/c9f409d4-d18c-11e5-95a4-f177bcc197eb.png)

**Comment by jamesnine** [comment]
hmm, I see your point, and the highlighting isn't working properly with HTML commenting; however, wouldn't it just look better to use handlebars for commenting instead?  You are writing on a blade template after all.

i.e. do this (use handlebars, since you're using a blade template:
`{{-- @include('test') --}}`

instead of this:
`<!-- @include('test') -->`

Also, using `//` commenting won't work outside of the `<?php` wrapper.  Do this instead (simply add two dashes inside each end:
`{{-- $test --}}`

Or, do it inside the `<?php` wrapper:
```
<?php
// {{ $test }}
```

**Comment by jdavidbakr** [comment]
@jamesnine - that's what I'm wanting to do - the comments I'm showing are what happens when I choose 'toggle_comment' (default super+forward_slash by default).  Before the SublimeText update I would do that keystroke and it would always do the handlebars, now it's doing the HTML comments and the // for a line with {{ }}.  I should have been more clear in my original post - I'm not reporting a bug with the styling, I'm reporting a bug with the toggle_comment keystroke.

**Comment by gwenzek** [comment]
I've never used this plugin, but this [commit](https://github.com/Medalink/laravel-blade/commit/711179b7dc07824f218dee7855f38a0829672efc) removed the file (Comment.tmPreferences) telling Sublime how to comment, so it's normal that it doesn't work anymore.

**Comment by alexmccabe** [comment]
@gwenzek Whether or not it's "normal" doesn't mean that it was the right thing to do, this is the exact same issue that I am facing. I want to comment out blade-syntax PHP, HTML comments will not do this. 

    

Naturally, that will do nothing. The PHP will still run.

**Comment by gwenzek** [comment]
All I'm saying is you should try to add back the "Comment.tmPreferences" back and see if it works again.
And as I'm not using the plugin and don't know what's 'Blade' I'm not the best suited for testing it.

**Comment by overcrookd** [comment]
Did the steps above, the issue remains, Sublime version: 3103

It's commenting like so now: "//"

**Comment by enkay** [comment]
same issue

**Comment by stiefkn** [comment]
Same issue here. Since update to 3103, keystroke leads to html comments `<!-- -->`

**Comment by Hornet-Wing** [comment]
I am seeing the same issue. Installing 1.5.2 solved the issue but it's missing a lot of the updates and highlighting.

**Comment by gomako** [comment]
@gwenzek I have put the ````Comment.tmPreferences```` file into the master branch but not having any joy in getting it to pick it up that file. Maybe it's being overridden somewhere else? I don't really understand how to start to debug this but would love to fix it. I was wondering if because the language def has changed from xml to Yaml and there's some way of including the comments file that I'm missing?

**Comment by Medalink** [comment]
I re-added the old file back, can you manually install the package and see if it works? If not I will do some more testing. If I recall I removed this because ST3 changed the way they handled comment handlers and it worked out of the box with the re-write.

**Comment by gomako** [comment]
Not working for me, on OSX build 3103. Is it because instead of a ````laravel-blade.tmLanguage```` file, it's now a ````blade.sublime-syntax```` file? If I install the laravel 5 branch, commenting works as expected, but it's missing all the great new stuff.

**Comment by jdavidbakr** [comment]
I've never manually installed a Sublime Text extension before so I'm not sure if I'm doing something wrong, but I removed the old blade syntax highlighter and cloned this into the Sublime Text 3->Packages as the ReadMe describes - but it doesn't show up in Sublime Text as a formatting option after I re-install.

**Comment by zaynali53** [comment]
Fixed https://github.com/Medalink/laravel-blade/commit/a9a78e63f2d06713af75853a012c23088990dcb2

![fix](https://cloud.githubusercontent.com/assets/8646770/15963169/4312ca04-2f29-11e6-8871-b9bee36b77da.png)
