### ISSUE TITLE
Email address within <a> tag of blade template

### ISSUE THREAD

**Issue by lukewhitehouse** [Medalink/laravel-blade#94]
Whilst in a blade template, if you create a link that goes directly to an email address, it throws off the syntax highlighting.

Here's an example:

![](http://i.imgur.com/N7SeDDI.png)

**Comment by santigarcor** [comment]
This also happens when you use vuejs inline events

**Comment by jwmoreland** [comment]
Also happens if an input field has a value set to an email address.

**Comment by ctf0** [comment]
this is related to the `@` symbol have the same scope as the extension `"ex.@section"`

**Comment by Medalink** [comment]
This has been fixed.
