### ISSUE TITLE
Highlighting breaks when using vue events

### ISSUE THREAD

**Issue by santigarcor** [Medalink/laravel-blade#97]
When i'm using things like this inside a .blade.php file: 
```html
<div @click="delete(something)"></div>
```

**Comment by shituser** [comment]
Same issue here. Syntax breaks if you use `@event="method()"` syntax on any html element.

**Comment by jartaud** [comment]
Same here. This breaks: `<a href="#!" @click="showForm()">Click</a>`

**Comment by BrandonSurowiec** [comment]
This should be fixed since Vue is pretty much the official JS Framework for Laravel.

**Comment by gabrielkoerich** [comment]
Please fix it

**Comment by Medalink** [comment]
This is a known limitation with the plugin. Currently there is no way (that I know of) to handle multiple inline highlighters. That means that we get inline PHP highlighting and nothing else.

**Comment by troygilbert** [comment]
Would be awesome if this was fixable, perhaps it could be re-investigated to see if possible?
