### ISSUE TITLE
end of comment highlight

### ISSUE THREAD

**Issue by ctf0** [Medalink/laravel-blade#99]
i know that this is one of the issues related to the new syntax formatting, but i was able to fix that by just appending the scope to the `-->` part in the html syntax file,

i tried to do the same to the blade file but without luck , so any tips on how to fix that :question:

**Comment by Medalink** [comment]
Is this still an issue after v1.5.8.3?

**Comment by ctf0** [comment]
fixed, thank you.

**Comment by ctf0** [comment]
broken again :(.

**Comment by exhtml** [comment]
yep, syntax highlighting broken again :(

**Comment by zaynali53** [comment]
@ctf0 Can you show me a code example?

**Comment by ctf0** [comment]
fixed with the last update, thanx.
